name: trickle
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  get_it: ^7.1.4
  bloc: ^7.0.0
  veee:
    path: ../veee
  api_call:
    path: ../api_call
  # flutter_bloc: ^7.0.1
  rxdart: ^0.27.1
  # OS
  url_launcher: ^6.0.7
  flutter_web_auth: ^0.3.0
  # Data & storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  json_annotation: ^4.0.1
  floor: ^1.1.0
  # Network
  http: ^0.13.0
  dio: ^4.0.0
  # Widgets & UI
  auto_route: ^2.2.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  animations: ^2.0.0
  palette_generator: ^0.3.0
  dotted_border: ^2.0.0+1
  supp:
    git: https://github.com/xiprox/sup
  # Util
  collection: ^1.15.0
  supercharged: ^2.0.0
  universal_io: ^2.0.4
  jwt_decoder: ^2.0.1
  crypto: ^3.0.1
  synchronized: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.5
  # Test
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.10
  # Generators
  json_serializable: ^5.0.2
  hive_generator: ^1.1.0
  auto_route_generator: ^2.1.0
  floor_generator: ^1.1.0

dependency_overrides:
  async: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/